version: '3.8'

services:
  url-shortener:
    container_name: url-shortener
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
    environment:
      - CONFIG_PATH=${CONFIG_PATH}
      - DB_PATH=${DB_PATH}
      - HTTP_PORT=${HTTP_PORT}
      - HTTP_ADDR=${HTTP_ADDR}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ${PWD}/storage:/storage
